---
# tasks file for soe
#

  - name: enable repos
    copy:
      src: open_three-tier-app.repo
      dest: /etc/yum.repos.d/open_three-tier-app.repo
      mode: 0644

  - name: disable and stop firewalld
    service:
      name: firewalld
      state: stopped
      enabled: false
    ignore_errors: yes
