- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
  -  aws_key.yml

  tasks:
  - name: Gather EC2 facts
    ec2_remote_facts:
      aws_access_key: "{{ aws_access_key_id }}"
      aws_secret_key: "{{ aws_secret_access_key }}"
      region: "{{ aws_region | default(region) | default('us-east-1')}}"
      filters:
        instance-state-name: running
        "tag:Project": "three-tier-app-*"
        "tag:owner": "jinzha@redhat.com"
    register: ec2_facts

  - name: debug ec2_facts
    debug:
      var: ec2_facts

  - name: build memoery inventory
    add_host:
      name: "{{item.public_dns_name}}"
      groups: "{{item.tags.AnsibleGroup}}"
    with_items: "{{ec2_facts['instances']}}"

  - name: debug hostvars
    debug:
      var: hostvars

- name: configuration
  hosts: frontends,apps,appdbs
  gather_facts: false 
  become: true
  roles:
  # SOE build - set repo and diable Firewall
  - role: soe

  # Configure haproxy serivce
  - role: haproxy
    when: "inventory_hostname in groups['frontends']"

  # Configure tomcat  serivce
  - role: tomcat
    when: "inventory_hostname in groups['apps']"

  # Configure postgres  serivce
  - role: postgres
    when: "inventory_hostname in groups['appdbs']"

  # Configure apach  serivce
  - role: apach
    when: "inventory_hostname in groups['apps']"



