- hosts: localhost
  connection: local
  gather_facts: false
  tasks:


  - name: Gather EC2 facts
    ec2_remote_facts:
      aws_access_key: "{{ aws_access_key_id }}"
      aws_secret_key: "{{ aws_secret_access_key }}"
      region: "{{ aws_region | default(region) | default('us-east-1')}}"
#      region: "{{ aws_region | default('ap-southeast-1')}}"
      filters:
        instance-state-name: running
#        "tag:Project": "{{project_tag}}"
        "tag:Project": "three-tier-app-*"
        "tag:owner": "jinzha@redhat.com"
    register: ec2_facts
#    tags:
#      - create_inventory
#      - must

  - name: debug ec2_facts
    debug:
      var: ec2_facts
#      verbosity: 2


