- hosts: localhost
  become: yes
  gather_facts: false
  tasks:
  - name: download RHEL image
    get_url:
      url: http://admin.na.shared.opentlc.com/repos/tower/small-rhel-cloud.qcow2
      dest: /root/small-rhel-cloud.qcow2
  - os_image:
      cloud: ospcloud
      name: rhel-guest-small
      container_format: bare
      disk_format: qcow2
      state: present
      filename: /root/small-rhel-cloud.qcow2
