
- name: Delete floating IP "{{ serverinfo.name }}"
  os_floating_ip:
    cloud: ospcloud
    state: "{{ ins_stat }}"
    reuse: yes
    server: "{{ serverinfo.name }}"
    network: ext_network
    wait: true

- name: Delete a server instance "{{ serverinfo.name }}"
  os_server:
    state: "{{ ins_stat }}"
    cloud: ospcloud
    name: "{{ serverinfo.name }}"
    image: rhel-guest-small
    meta: "group={{ serverinfo.group }},deployment_name={{ deployment }}"
    flavor: "{{ flavor_name }}"
    security_groups: ICMP_and_SSH
    key_name: ansible_ssh
    nics:
    - net-name: int_network
